### ISSUE TITLE
Firefox problems loading Swell model when reloading page

### ISSUE THREAD

**Issue by atfornes** [P2Pvalue/pear2pear#41] opened 2015-07-06 18:00 UTC
In production (not reproduced locally):
When reloading a page (e.g. https://p.p2pvalue.eu/#/communities) in Firefox with SwellRT model data, the data is not displayed. When doing it in chrome it does work as expected.

If adding a new community from another browser, the following  error messages appear in the Firefox console: https://p.p2pvalue.eu/#/communities: ```uncaught exception: java.lang.IllegalStateException: Received deltas with no stacklet present!``` Maybe this message helps @pablojan understanding the error :)

Behavior observed after  c4cc512, but the problem might happen in earlier releases.

**Comment by atd** [comment] 2015-07-07 08:27
FYI

Cannot reproduce with Iceweasel 38.0.1

**Comment by pablojan** [comment] 2015-07-07 08:30
I am working on it.

**Comment by atfornes** [comment] 2015-07-07 09:28
I can not reproduce it now, @pablojan, might it be solved by your last commits in SwellRT?

**Comment by pablojan** [comment] 2015-07-07 09:37
Yes, it should be fixed. I am going to make some manual tests now...

2015-07-07 11:28 GMT+02:00 atfornes <notifications@github.com>:

**Comment by atfornes** [comment] 2015-07-07 09:40
:tada::clap::clap::clap:

**Closed** 2015-09-23 08:57 UTC
Labels: swellrt
